"""Confirmatory analyses H1-H5 exactly as specified in ANALYSIS_PLAN.md (frozen 9 Oct 2026).

Outputs: outputs/confirmatory/*.csv and docs/confirmatory_generated.md.
Usage: python scripts/confirmatory.py [--config config.yaml]
Runtime: roughly 15-25 min on a laptop (20 leave-one-match-out folds with the reference rebuilt
inside each fold).
"""

from __future__ import annotations

import argparse
import copy
import time
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

from reorg import stats
from reorg.io import list_match_ids
from reorg.outcomes import OutcomeParams, add_danger, landmark_sample
from reorg.pipeline import prepare_match
from reorg.reference import build_reference, organised_frames
from reorg.reorganisation import ReorgParams, episodes_for_match, team_taus
from reorg.shape import COMPONENTS

ROOT = Path(__file__).resolve().parents[1]

# H2 covariates (ANALYSIS_PLAN.md §5, H2): 5 adjustment terms + the exposure.
COVARIATES = ["ball_x", "wide_channel", "goal_side_at_loss", "ball_speed_3s", "log1p_poss"]
REDUCED_COVARIATES = ["ball_x", "goal_side_at_loss"]
ZONE = ["ball_x", "wide_channel"]


def features(e: pd.DataFrame) -> pd.DataFrame:
    e = e.copy()
    e["wide_channel"] = ((e["cell"] % 3) != 1).astype(int)
    e["log1p_poss"] = np.log1p(e["a_possession_s"])
    return e


def fit_reference(mds_ref, cfg, P):
    ref = build_reference(organised_frames(mds_ref), cfg)
    return ref, team_taus(mds_ref, ref, P)


def episodes(mds_ref, mds_eval, cfg, P, OP, min_frame_det=None, fitted=None):
    """Reference and tau from ``mds_ref`` (or ``fitted``); episodes (+ danger) for ``mds_eval``."""
    ref, taus = fitted or fit_reference(mds_ref, cfg, P)
    out = []
    for md in mds_eval:
        e = episodes_for_match(md, ref, taus, P, min_frame_det=min_frame_det)[0]
        out.append(add_danger(md, e, OP))
    return features(pd.concat(out, ignore_index=True))


def landmark(e: pd.DataFrame, lm: float) -> pd.DataFrame:
    s = landmark_sample(e, lm)
    s = s[np.isfinite(s[COVARIATES]).all(axis=1)].copy()
    s["nn_mean"] = s[f"nn_mean_0_{lm:g}s"]
    s["phase_org"] = s[f"phase_organised_at_{lm:g}s"].astype(int)
    return s


def md_table(df: pd.DataFrame, digits: int = 3) -> str:
    df = df.round(digits)
    lines = ["| " + " | ".join(map(str, df.columns)) + " |", "|" + "---|" * len(df.columns)]
    lines += [
        "| " + " | ".join("" if pd.isna(v) else str(v) for v in r) + " |"
        for r in df.itertuples(index=False)
    ]
    return "\n".join(lines)


def h2(sample: pd.DataFrame, cc: dict, seed: int, exposure: str = "still_disorganised") -> dict:
    n_events = int(sample["y"].sum())
    cov = COVARIATES if n_events >= cc["min_events_full_model"] else REDUCED_COVARIATES
    X = [exposure, *cov]
    r = stats.cluster_bootstrap_or(sample, "y", X, exposure, cc["n_boot"], seed)
    r.update(
        {
            "episodes": len(sample),
            "events": n_events,
            "model": "full" if cov is COVARIATES else "reduced",
            "p_one_sided": stats.wald_one_sided_p(sample, "y", X, exposure, "match_id"),
        }
    )
    return r


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=str(ROOT / "config.yaml"))
    a = ap.parse_args()
    cfg = yaml.safe_load(Path(a.config).read_text())
    cc = cfg["confirmatory"]
    seed = int(cfg["prototype"]["seed"])
    P, OP = ReorgParams.from_config(cfg), OutcomeParams.from_config(cfg)
    det_thr = float(cfg["reliability"]["frame_min_detected"])
    rel_thr = float(cfg["reliability"]["episode_min_reliability"])
    out = ROOT / "outputs" / "confirmatory"
    out.mkdir(parents=True, exist_ok=True)
    root, cache = str(ROOT / cfg["data"]["root"]), str(ROOT / cfg["data"]["cache"])
    t0 = time.time()
    mds = [prepare_match(root, m, cfg, cache) for m in list_match_ids(root)]
    names = {}
    for md in mds:
        names[md.meta.home_team_id] = md.meta.home_team_name
        names[md.meta.away_team_id] = md.meta.away_team_name

    # Full-data episodes (H1, H2, H3, H5-for-H2).
    full = fit_reference(mds, cfg, P)
    e_all = episodes(mds, mds, cfg, P, OP, fitted=full)
    e_det = episodes(mds, mds, cfg, P, OP, min_frame_det=det_thr, fitted=full)
    e_all.to_csv(out / "episodes_with_outcome.csv", index=False)
    dis = e_all[e_all["disorganised_at_loss"]]
    lines = [
        "<!-- generated by scripts/confirmatory.py; do not edit by hand -->",
        "",
        "All analyses below are **confirmatory** (ANALYSIS_PLAN.md, frozen 9 Oct 2026) unless "
        "marked otherwise.",
        "",
    ]
    danger_desc = pd.DataFrame(
        [
            {
                "set": "all losses",
                "episodes": len(e_all),
                "danger": int(np.isfinite(e_all["t_danger"]).sum()),
            },
            {
                "set": "disorganised at loss",
                "episodes": len(dis),
                "danger": int(np.isfinite(dis["t_danger"]).sum()),
            },
        ]
    )
    danger_desc["rate"] = danger_desc["danger"] / danger_desc["episodes"]
    types = dis["danger_type"].replace("", np.nan).value_counts().to_dict()
    lines += [
        "### Outcome prevalence (descriptive)",
        "",
        md_table(danger_desc),
        "",
        f"Danger types among disorganised-at-loss episodes: {types}",
        "",
    ]

    # ---------------------------------------------------------------- H1
    h = float(cc["primary_horizon_s"])
    perm = stats.permutation_team_effect(dis, h, cc["n_perm"], seed)
    sh = stats.split_half_reliability(dis, h)
    lines += [
        "### H1: teams differ in reorganisation speed",
        "",
        f"- Variance of team P(reorganised by {h:g} s): {perm['statistic']:.5f} vs permutation "
        f"null mean {perm['null_mean']:.5f}; one-sided p = {perm['p_value']:.4f} "
        f"({cc['n_perm']} match-preserving permutations).",
        f"- Odd/even split-half: r = {sh['r']:.2f}, Spearman-Brown = {sh['spearman_brown']:.2f} "
        f"({sh['teams']} teams). Pre-set reading: SB >= 0.5 = moderately reliable.",
        "",
    ]

    # ---------------------------------------------------------------- H2 (+ secondary)
    h2_rows = []
    for lm in cfg["outcomes"]["landmarks_s"]:
        s = landmark(e_all, lm)
        r = h2(s, cc, seed)
        h2_rows.append({"analysis": f"binary still-disorganised, landmark {lm:g} s", **r})
        s = s.copy()
        s["log_D_sd"] = (s["log_D"] - s["log_D"].mean()) / s["log_D"].std()
        r = h2(s, cc, seed, exposure="log_D_sd")
        h2_rows.append({"analysis": f"log D per SD, landmark {lm:g} s (secondary)", **r})
    h2_tab = pd.DataFrame(h2_rows)
    h2_tab.to_csv(out / "h2.csv", index=False)
    lines += [
        "### H2: still disorganised at the landmark -> dangerous attack afterwards",
        "",
        "Primary = first row (binary exposure, 3 s landmark). OR > 1 was pre-specified.",
        "",
        md_table(
            h2_tab[["analysis", "episodes", "events", "model", "or", "lo", "hi", "p_one_sided"]]
        ),
        "",
    ]

    # ---------------------------------------------------------------- H3
    sh3 = stats.component_shares(dis, COMPONENTS, h, cc["n_boot"], seed)
    cfg_f = copy.deepcopy(cfg)
    cfg_f["reference"]["spread_floor"]["goal_side"] = 1.0
    e_f = episodes(mds, mds, cfg_f, P, OP)
    sh3f = stats.component_shares(
        e_f[e_f["disorganised_at_loss"]], COMPONENTS, h, cc["n_boot"], seed
    )
    sh3.to_csv(out / "h3.csv", index=False)
    lines += [
        "### H3: which component carries the remaining disorganisation (+6 s)",
        "",
        md_table(sh3),
        "",
        f"- Late episodes: {sh3.attrs['late_episodes']}. Largest minus second: "
        f"{sh3.attrs['top_minus_second']:.3f} [{sh3.attrs['gap_lo']:.3f}, "
        f"{sh3.attrs['gap_hi']:.3f}], one-sided p = {sh3.attrs['p_gap_le_0']:.4f}.",
        f"- Robustness (goal-side floor 1.0): largest = {sh3f.iloc[0]['component']} "
        f"({sh3f.iloc[0]['share']:.3f}), second = {sh3f.iloc[1]['component']} "
        f"({sh3f.iloc[1]['share']:.3f}); gap CI [{sh3f.attrs['gap_lo']:.3f}, "
        f"{sh3f.attrs['gap_hi']:.3f}].",
        "",
    ]

    # ---------------------------------------------------------------- H4 (+ H5) LOMO
    lm = float(cfg["outcomes"]["landmarks_s"][0])
    models = {
        "M_zone": ZONE,
        "M_cov": COVARIATES,
        "M_D": ["still_disorganised", *COVARIATES],
        "M_compact": ["nn_mean", *COVARIATES],
        "M_phase": ["phase_org", *COVARIATES],
        "M_compact+D": ["nn_mean", "still_disorganised", *COVARIATES],
        "M_phase+D": ["phase_org", "still_disorganised", *COVARIATES],
    }
    preds = {reg: [] for reg in ("all", "detected", "reliable")}
    ids = [md.meta.match_id for md in mds]
    for k, mid in enumerate(ids):
        train = [md for md in mds if md.meta.match_id != mid]
        test = [md for md in mds if md.meta.match_id == mid]
        fitted = fit_reference(train, cfg, P)
        cache_eps = {}
        for reg in ("all", "detected", "reliable"):
            mfd = det_thr if reg == "detected" else None
            key = "detected" if reg == "detected" else "all"
            if key not in cache_eps:
                cache_eps[key] = (
                    landmark(episodes(train, train, cfg, P, OP, mfd, fitted), lm),
                    landmark(episodes(train, test, cfg, P, OP, mfd, fitted), lm),
                )
            tr, te = cache_eps[key]
            if reg == "reliable":
                tr = tr[tr["reliability_10s"] >= rel_thr]
                te = te[te["reliability_10s"] >= rel_thr]
            if te.empty:
                continue
            row = te[["match_id", "frame_loss", "y"]].copy()
            for name, X in models.items():
                if reg != "all" and name not in ("M_cov", "M_D"):
                    continue
                fit = stats.fit_logit(tr, "y", X)
                row[name] = fit.predict(
                    stats.sm.add_constant(te[X].astype(float), has_constant="add")
                ).to_numpy()
            preds[reg].append(row)
        print(f"fold {k + 1}/{len(ids)} done ({time.time() - t0:.0f} s)", flush=True)
    comp_rows = []
    pairs_all = [
        ("M_D", "M_cov", "primary"),
        ("M_cov", "M_zone", "secondary"),
        ("M_D", "M_compact", "secondary"),
        ("M_D", "M_phase", "secondary"),
        ("M_compact+D", "M_compact", "secondary"),
        ("M_phase+D", "M_phase", "secondary"),
    ]
    h4_p = {}
    for reg, rows in preds.items():
        pr = pd.concat(rows, ignore_index=True)
        pr.to_csv(out / f"h4_predictions_{reg}.csv", index=False)
        y, cl = pr["y"].to_numpy(), pr["match_id"].to_numpy()
        for a_, b_, role in pairs_all if reg == "all" else [("M_D", "M_cov", "primary")]:
            d = stats.paired_metric_diff(
                y, pr[a_].to_numpy(), pr[b_].to_numpy(), cl, cc["n_boot"], seed
            ).set_index("metric")
            p = stats.bootstrap_one_sided_p(
                y, pr[a_].to_numpy(), pr[b_].to_numpy(), cl, cc["n_boot"], seed
            )
            if reg == "all" and role == "primary":
                h4_p["H4"] = p
            comp_rows.append(
                {
                    "regime": reg,
                    "comparison": f"{a_} vs {b_}",
                    "role": role,
                    "episodes": len(pr),
                    "events": int(y.sum()),
                    "dlogloss": d.loc["log_loss", "diff"],
                    "dlogloss_lo": d.loc["log_loss", "lo"],
                    "dlogloss_hi": d.loc["log_loss", "hi"],
                    "p_one_sided": p,
                    "dbrier": d.loc["brier", "diff"],
                    "dauc": d.loc["auc", "diff"],
                    "dauc_lo": d.loc["auc", "lo"],
                    "dauc_hi": d.loc["auc", "hi"],
                }
            )
    h4_tab = pd.DataFrame(comp_rows)
    h4_tab.to_csv(out / "h4.csv", index=False)
    auc_tab = []
    pr_all = pd.concat(preds["all"], ignore_index=True)
    for name in models:
        auc_tab.append(
            {
                "model": name,
                "auc": stats.auc(pr_all["y"].to_numpy(), pr_all[name].to_numpy()),
                "log_loss": stats.log_loss(pr_all["y"].to_numpy(), pr_all[name].to_numpy()),
            }
        )
    lines += [
        "### H4: out-of-fold predictive value (leave-one-match-out, reference rebuilt per fold)",
        "",
        "Negative dlogloss favours the first model; CI upper bound < 0 = adds value.",
        "",
        md_table(
            h4_tab[
                [
                    "regime",
                    "comparison",
                    "role",
                    "episodes",
                    "events",
                    "dlogloss",
                    "dlogloss_lo",
                    "dlogloss_hi",
                    "p_one_sided",
                    "dauc",
                    "dauc_lo",
                    "dauc_hi",
                ]
            ],
            4,
        ),
        "",
        "Out-of-fold AUC / log-loss per model (all regime):",
        "",
        md_table(pd.DataFrame(auc_tab), 4),
        "",
    ]

    # ---------------------------------------------------------------- H5 for H2
    h5 = []
    for reg, ee in (("all", e_all), ("detected", e_det)):
        s = landmark(ee, lm)
        h5.append({"regime": reg, **h2(s, cc, seed)})
    s = landmark(e_all, lm)
    h5.append({"regime": "reliable", **h2(s[s["reliability_10s"] >= rel_thr], cc, seed)})
    h5_tab = pd.DataFrame(h5)
    lines += [
        "### H5: H2 primary OR across reliability regimes (H4 regimes are in the H4 table)",
        "",
        md_table(
            h5_tab[["regime", "episodes", "events", "model", "or", "lo", "hi", "p_one_sided"]]
        ),
        "",
    ]

    # ---------------------------------------------------------------- Holm
    pv = {
        "H1": perm["p_value"],
        "H2": float(h2_tab.iloc[0]["p_one_sided"]),
        "H3": sh3.attrs["p_gap_le_0"],
        **h4_p,
    }
    hm = stats.holm(pv, float(cc["alpha"]))
    hm.to_csv(out / "holm.csv", index=False)
    lines += [
        "### Holm correction across the four primary tests",
        "",
        md_table(hm, 4),
        "",
        f"Runtime: {time.time() - t0:.0f} s.",
        "",
    ]
    (ROOT / "docs" / "confirmatory_generated.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
