"""Confirmatory analyses H1-H5 exactly as specified in ANALYSIS_PLAN.md (frozen 9 Oct 2026).

Outputs: outputs/confirmatory/*.csv and docs/confirmatory_generated.md.
Usage: python scripts/confirmatory.py [--config config.yaml]
Runtime: about 40 min single-process; folds run in parallel with --workers (default 4).
"""

from __future__ import annotations

import argparse
import copy
import time
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

from reorg import stats
from reorg.io import list_match_ids
from reorg.pipeline import prepare_match
from reorg.shape import COMPONENTS
from reorg.validation import (
    MODELS,
    Variant,
    compare,
    cv_predictions,
    episodes_with_outcome,
    fit_reference,
    h2_effect,
    landmark,
)

ROOT = Path(__file__).resolve().parents[1]


def md_table(df: pd.DataFrame, digits: int = 3) -> str:
    df = df.round(digits)
    lines = ["| " + " | ".join(map(str, df.columns)) + " |", "|" + "---|" * len(df.columns)]
    lines += [
        "| " + " | ".join("" if pd.isna(v) else str(v) for v in r) + " |"
        for r in df.itertuples(index=False)
    ]
    return "\n".join(lines)


def h2(sample: pd.DataFrame, cc: dict, seed: int, exposure: str = "still_disorganised") -> dict:
    return h2_effect(sample, cc["n_boot"], seed, cc["min_events_full_model"], exposure)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=str(ROOT / "config.yaml"))
    ap.add_argument("--workers", type=int, default=4, help="parallel folds (results do not change)")
    a = ap.parse_args()
    cfg = yaml.safe_load(Path(a.config).read_text())
    cc = cfg["confirmatory"]
    seed = int(cfg["prototype"]["seed"])
    v = Variant(cfg)
    det_thr = float(cfg["reliability"]["frame_min_detected"])
    rel_thr = float(cfg["reliability"]["episode_min_reliability"])
    out = ROOT / "outputs" / "confirmatory"
    out.mkdir(parents=True, exist_ok=True)
    root, cache = str(ROOT / cfg["data"]["root"]), str(ROOT / cfg["data"]["cache"])
    t0 = time.time()
    mds = [prepare_match(root, m, cfg, cache) for m in list_match_ids(root)]
    names = {}
    for md in mds:
        names[md.meta.home_team_id] = md.meta.home_team_name
        names[md.meta.away_team_id] = md.meta.away_team_name

    # Full-data episodes (H1, H2, H3, H5-for-H2).
    full = fit_reference(mds, v)
    e_all = episodes_with_outcome(mds, mds, v, fitted=full)
    e_det = episodes_with_outcome(mds, mds, v, min_frame_det=det_thr, fitted=full)
    e_all.to_csv(out / "episodes_with_outcome.csv", index=False)
    dis = e_all[e_all["disorganised_at_loss"]]
    lines = [
        "<!-- generated by scripts/confirmatory.py; do not edit by hand -->",
        "",
        "All analyses below are **confirmatory** (ANALYSIS_PLAN.md, frozen 9 Oct 2026) unless "
        "marked otherwise.",
        "",
    ]
    danger_desc = pd.DataFrame(
        [
            {
                "set": "all losses",
                "episodes": len(e_all),
                "danger": int(np.isfinite(e_all["t_danger"]).sum()),
            },
            {
                "set": "disorganised at loss",
                "episodes": len(dis),
                "danger": int(np.isfinite(dis["t_danger"]).sum()),
            },
        ]
    )
    danger_desc["rate"] = danger_desc["danger"] / danger_desc["episodes"]
    types = dis["danger_type"].replace("", np.nan).value_counts().to_dict()
    lines += [
        "### Outcome prevalence (descriptive)",
        "",
        md_table(danger_desc),
        "",
        f"Danger types among disorganised-at-loss episodes: {types}",
        "",
    ]

    # ---------------------------------------------------------------- H1
    h = float(cc["primary_horizon_s"])
    perm = stats.permutation_team_effect(dis, h, cc["n_perm"], seed)
    sh = stats.split_half_reliability(dis, h)
    lines += [
        "### H1: teams differ in reorganisation speed",
        "",
        f"- Variance of team P(reorganised by {h:g} s): {perm['statistic']:.5f} vs permutation "
        f"null mean {perm['null_mean']:.5f}; one-sided p = {perm['p_value']:.4f} "
        f"({cc['n_perm']} match-preserving permutations).",
        f"- Odd/even split-half: r = {sh['r']:.2f}, Spearman-Brown = {sh['spearman_brown']:.2f} "
        f"({sh['teams']} teams). Pre-set reading: SB >= 0.5 = moderately reliable.",
        "",
    ]

    # ---------------------------------------------------------------- H2 (+ secondary)
    h2_rows = []
    for lm in cfg["outcomes"]["landmarks_s"]:
        s = landmark(e_all, lm)
        r = h2(s, cc, seed)
        h2_rows.append({"analysis": f"binary still-disorganised, landmark {lm:g} s", **r})
        s = s.copy()
        s["log_D_sd"] = (s["log_D"] - s["log_D"].mean()) / s["log_D"].std()
        r = h2(s, cc, seed, exposure="log_D_sd")
        h2_rows.append({"analysis": f"log D per SD, landmark {lm:g} s (secondary)", **r})
    h2_tab = pd.DataFrame(h2_rows)
    h2_tab.to_csv(out / "h2.csv", index=False)
    lines += [
        "### H2: still disorganised at the landmark -> dangerous attack afterwards",
        "",
        "Primary = first row (binary exposure, 3 s landmark). OR > 1 was pre-specified.",
        "",
        md_table(
            h2_tab[["analysis", "episodes", "events", "model", "or", "lo", "hi", "p_one_sided"]]
        ),
        "",
    ]

    # ---------------------------------------------------------------- H3
    sh3 = stats.component_shares(dis, COMPONENTS, h, cc["n_boot"], seed)
    cfg_f = copy.deepcopy(cfg)
    cfg_f["reference"]["spread_floor"]["goal_side"] = 1.0
    e_f = episodes_with_outcome(mds, mds, Variant(cfg_f))
    sh3f = stats.component_shares(
        e_f[e_f["disorganised_at_loss"]], COMPONENTS, h, cc["n_boot"], seed
    )
    sh3.to_csv(out / "h3.csv", index=False)
    lines += [
        "### H3: which component carries the remaining disorganisation (+6 s)",
        "",
        md_table(sh3),
        "",
        f"- Late episodes: {sh3.attrs['late_episodes']}. Largest minus second: "
        f"{sh3.attrs['top_minus_second']:.3f} [{sh3.attrs['gap_lo']:.3f}, "
        f"{sh3.attrs['gap_hi']:.3f}], one-sided p = {sh3.attrs['p_gap_le_0']:.4f}.",
        f"- Robustness (goal-side floor 1.0): largest = {sh3f.iloc[0]['component']} "
        f"({sh3f.iloc[0]['share']:.3f}), second = {sh3f.iloc[1]['component']} "
        f"({sh3f.iloc[1]['share']:.3f}); gap CI [{sh3f.attrs['gap_lo']:.3f}, "
        f"{sh3f.attrs['gap_hi']:.3f}].",
        "",
    ]

    # ---------------------------------------------------------------- H4 (+ H5) LOMO
    lm = float(cfg["outcomes"]["landmarks_s"][0])
    models = MODELS

    def progress(k: int, n: int) -> None:
        print(f"fold {k}/{n} done ({time.time() - t0:.0f} s)", flush=True)

    preds = cv_predictions(
        mds, v, lm, det_thr, rel_thr, folds=0, workers=a.workers, progress=progress
    )
    comp_rows = []
    pairs_all = [
        ("M_D", "M_cov", "primary"),
        ("M_cov", "M_zone", "secondary"),
        ("M_D", "M_compact", "secondary"),
        ("M_D", "M_phase", "secondary"),
        ("M_compact+D", "M_compact", "secondary"),
        ("M_phase+D", "M_phase", "secondary"),
    ]
    h4_p = {}
    for reg, pr in preds.items():
        pr.to_csv(out / f"h4_predictions_{reg}.csv", index=False)
        for a_, b_, role in pairs_all if reg == "all" else [("M_D", "M_cov", "primary")]:
            r = compare(pr, a_, b_, cc["n_boot"], seed)
            if reg == "all" and role == "primary":
                h4_p["H4"] = r["p_one_sided"]
            comp_rows.append({"regime": reg, "role": role, **r})
    h4_tab = pd.DataFrame(comp_rows)
    h4_tab.to_csv(out / "h4.csv", index=False)
    auc_tab = []
    pr_all = preds["all"]
    for name in models:
        auc_tab.append(
            {
                "model": name,
                "auc": stats.auc(pr_all["y"].to_numpy(), pr_all[name].to_numpy()),
                "log_loss": stats.log_loss(pr_all["y"].to_numpy(), pr_all[name].to_numpy()),
            }
        )
    lines += [
        "### H4: out-of-fold predictive value (leave-one-match-out, reference rebuilt per fold)",
        "",
        "Negative dlogloss favours the first model; CI upper bound < 0 = adds value.",
        "",
        md_table(
            h4_tab[
                [
                    "regime",
                    "comparison",
                    "role",
                    "episodes",
                    "events",
                    "dlogloss",
                    "dlogloss_lo",
                    "dlogloss_hi",
                    "p_one_sided",
                    "dauc",
                    "dauc_lo",
                    "dauc_hi",
                ]
            ],
            4,
        ),
        "",
        "Out-of-fold AUC / log-loss per model (all regime):",
        "",
        md_table(pd.DataFrame(auc_tab), 4),
        "",
    ]

    # ---------------------------------------------------------------- H5 for H2
    h5 = []
    for reg, ee in (("all", e_all), ("detected", e_det)):
        s = landmark(ee, lm)
        h5.append({"regime": reg, **h2(s, cc, seed)})
    s = landmark(e_all, lm)
    h5.append({"regime": "reliable", **h2(s[s["reliability_10s"] >= rel_thr], cc, seed)})
    h5_tab = pd.DataFrame(h5)
    lines += [
        "### H5: H2 primary OR across reliability regimes (H4 regimes are in the H4 table)",
        "",
        md_table(
            h5_tab[["regime", "episodes", "events", "model", "or", "lo", "hi", "p_one_sided"]]
        ),
        "",
    ]

    # ---------------------------------------------------------------- Holm
    pv = {
        "H1": perm["p_value"],
        "H2": float(h2_tab.iloc[0]["p_one_sided"]),
        "H3": sh3.attrs["p_gap_le_0"],
        **h4_p,
    }
    hm = stats.holm(pv, float(cc["alpha"]))
    hm.to_csv(out / "holm.csv", index=False)
    lines += [
        "### Holm correction across the four primary tests",
        "",
        md_table(hm, 4),
        "",
        f"Runtime: {time.time() - t0:.0f} s.",
        "",
    ]
    (ROOT / "docs" / "confirmatory_generated.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
