"""Pre-registered sensitivity of the primary effects (ANALYSIS_PLAN.md §6).

For every variant: the H2 primary odds ratio (3 s landmark, match-cluster bootstrap CI) and the
H4 primary comparison (M_D vs M_cov, out-of-fold log-loss difference, leave-one-match-out).
To keep the run short, variants use the reference built from all matches (it uses shape data
only, never outcomes); the frozen confirmatory H4 rebuilds it inside every fold instead.
Writes outputs/sensitivity/effects.csv and docs/sensitivity_effects_generated.md.

Usage: python scripts/sensitivity_effects.py [--config config.yaml]
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import yaml

from reorg import stats
from reorg.io import list_match_ids
from reorg.pipeline import prepare_match
from reorg.validation import (
    COVARIATES,
    compare,
    episodes_with_outcome,
    h2_effect,
    landmark,
    sensitivity_variants,
)

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=str(ROOT / "config.yaml"))
    a = ap.parse_args()
    cfg = yaml.safe_load(Path(a.config).read_text())
    cc = cfg["confirmatory"]
    seed = int(cfg["prototype"]["seed"])
    lm = float(cfg["outcomes"]["landmarks_s"][0])
    root, cache = str(ROOT / cfg["data"]["root"]), str(ROOT / cfg["data"]["cache"])
    out = ROOT / "outputs" / "sensitivity"
    out.mkdir(parents=True, exist_ok=True)
    mds = [prepare_match(root, m, cfg, cache) for m in list_match_ids(root)]
    rows = []
    for name, v in sensitivity_variants(cfg):
        s = landmark(episodes_with_outcome(mds, mds, v), lm)
        h2 = h2_effect(s, cc["n_boot"], seed, cc["min_events_full_model"])
        pred = s[["match_id", "frame_loss", "y"]].copy()
        for m, X in (("M_cov", COVARIATES), ("M_D", ["still_disorganised", *COVARIATES])):
            pred[m] = stats.lomo_predict(s, "y", X)
        h4 = compare(pred, "M_D", "M_cov", cc["n_boot"], seed)
        rows.append(
            {
                "variant": name,
                "episodes": h2["episodes"],
                "events": h2["events"],
                "h2_or": h2["or"],
                "h2_lo": h2["lo"],
                "h2_hi": h2["hi"],
                "h4_dlogloss": h4["dlogloss"],
                "h4_lo": h4["dlogloss_lo"],
                "h4_hi": h4["dlogloss_hi"],
            }
        )
        print(rows[-1], flush=True)
    tab = pd.DataFrame(rows)
    tab.to_csv(out / "effects.csv", index=False)
    t = tab.round(4)
    lines = [
        "<!-- generated by scripts/sensitivity_effects.py; do not edit by hand -->",
        "",
        "Pre-registered sensitivity of the primary effects. H2: OR of still-disorganised at "
        "3 s (95% match bootstrap). H4: out-of-fold log-loss of M_D minus M_cov "
        "(leave-one-match-out; negative favours D). Variants use the all-match reference.",
        "",
        "| " + " | ".join(t.columns) + " |",
        "|" + "---|" * len(t.columns),
    ]
    lines += ["| " + " | ".join(map(str, r)) + " |" for r in t.itertuples(index=False)]
    (ROOT / "docs" / "sensitivity_effects_generated.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
