"""Pre-registered sensitivity grid for the reorganisation metric (no outcome variables).

For each variant: number of disorganised-at-loss episodes, league cumulative incidence of
reorganisation at 3/6/10 s, Spearman correlation of team P(reorg by 6 s) with the base run, and
Spearman correlation of episode T_r with the base run (episodes reorganised in both).
Writes outputs/sensitivity/grid.csv and docs/sensitivity_generated.md.

Usage: python scripts/sensitivity.py [--config config.yaml]
"""

from __future__ import annotations

import argparse
import copy
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

from reorg.io import list_match_ids
from reorg.pipeline import prepare_match
from reorg.reference import build_reference, organised_frames
from reorg.reorganisation import ReorgParams, episodes_for_match, team_summary, team_taus
from reorg.survival import cumulative_incidence

ROOT = Path(__file__).resolve().parents[1]
HORIZONS_S = (3.0, 6.0, 10.0)


def variants(cfg: dict) -> list[tuple[str, dict, dict]]:
    """(name, config, options) for every pre-registered variant (ANALYSIS_PLAN.md §S)."""
    out = [("base", cfg, {})]

    def mod(name, fn, **opts):
        c = copy.deepcopy(cfg)
        fn(c)
        out.append((name, c, opts))

    for q in (0.70, 0.80):
        mod(f"tau_q={q}", lambda c, q=q: c["reorganisation"].__setitem__("tau_quantile", q))
    for h in (1.5, 3.0):
        mod(f"hold={h}s", lambda c, h=h: c["reorganisation"].__setitem__("hold_s", h))
    mod("discrete_reference", lambda c: None, continuous=False)
    mod("league_only_reference", lambda c: None, team_specific=False)
    mod(
        "goal_side_floor=1.0",
        lambda c: c["reference"]["spread_floor"].__setitem__("goal_side", 1.0),
    )
    mod("no_goal_side", lambda c: c["shape"]["weights"].__setitem__("goal_side", 0.0))
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=str(ROOT / "config.yaml"))
    a = ap.parse_args()
    cfg = yaml.safe_load(Path(a.config).read_text())
    root, cache = str(ROOT / cfg["data"]["root"]), str(ROOT / cfg["data"]["cache"])
    out = ROOT / "outputs" / "sensitivity"
    out.mkdir(parents=True, exist_ok=True)
    mds = [prepare_match(root, m, cfg, cache) for m in list_match_ids(root)]
    org = organised_frames(mds)

    rows, base_eps, base_team = [], None, None
    for name, c, opts in variants(cfg):
        cont = opts.get("continuous", True)
        ref = build_reference(org, c, team_specific=opts.get("team_specific", True))
        P = ReorgParams.from_config(c)
        taus = team_taus(mds, ref, P, continuous=cont)
        eps = pd.concat(
            [episodes_for_match(md, ref, taus, P, continuous=cont)[0] for md in mds],
            ignore_index=True,
        )
        dis = eps[eps["disorganised_at_loss"]]
        cif = cumulative_incidence(dis["time_s"], dis["code"], np.array(HORIZONS_S))
        team = team_summary(eps).set_index("losing_team_id")
        row = {
            "variant": name,
            "disorganised_episodes": len(dis),
            "share_organised_at_loss": float(1 - eps["disorganised_at_loss"].mean()),
        }
        row.update(
            {f"reorg_by_{h:g}s": float(v) for h, v in zip(HORIZONS_S, cif["cif_1"], strict=True)}
        )
        if base_eps is None:
            base_eps, base_team = eps, team
            row["team_rank_rho"], row["episode_T_r_rho"] = 1.0, 1.0
        else:
            t = team[["reorg_by_6s"]].join(base_team[["reorg_by_6s"]], rsuffix="_b").dropna()
            row["team_rank_rho"] = float(t.corr(method="spearman").iloc[0, 1])
            m = eps.merge(base_eps, on=["match_id", "frame_loss"], suffixes=("", "_b"))
            m = m[m["reorganised"] & m["reorganised_b"]]
            row["episode_T_r_rho"] = float(m[["T_r", "T_r_b"]].corr(method="spearman").iloc[0, 1])
        rows.append(row)
        print(row, flush=True)
    grid = pd.DataFrame(rows)
    grid.to_csv(out / "grid.csv", index=False)
    g = grid.round(3)
    lines = [
        "<!-- generated by scripts/sensitivity.py; do not edit by hand -->",
        "",
        "| " + " | ".join(g.columns) + " |",
        "|" + "---|" * len(g.columns),
    ]
    lines += ["| " + " | ".join(map(str, r)) + " |" for r in g.itertuples(index=False)]
    (ROOT / "docs" / "sensitivity_generated.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
